version: '3.2'

services:
  server:
    container_name: dayscout-server
    build: .
    ports:
      - "${SERVER_PORT?}:80"
    environment:
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=${ES_INDEX}
      - CLOVA_API_URL=${CLOVA_API_URL}
      - CLOVA_CLIENT_SECRET=${CLOVA_CLIENT_SECRET?}
    networks:
      - server
    depends_on:
      - elasticsearch

  elasticsearch:
    container_name: dayscout-elasticsearch
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./data
        target: /usr/share/elasticsearch/data
    ports:
      - "${ES_PORT?}:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ${ES_PASSWORD?}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks
      # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
      - server

  kibana:
    container_name: dayscout-kibana
    build:
      context: kibana/
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "${KIBANA_PORT?}:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
  server:
    driver: bridge
